/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9ccf7d8a290473f153371cedcc56519b)
interface __BaseEnv_Env {
	X402_FACILITATOR_URL: "https://x402.org/facilitator";
	X402_NETWORK: "eip155:8453";
	WorkchainMCP: DurableObjectNamespace<import("./src/server").WorkchainMCP>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "WorkchainMCP";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "X402_FACILITATOR_URL" | "X402_NETWORK">> {}
}
